Repository acm-ucr/asme-website, pull requests merged in 2023-09, with the labels that each got.

#101 Add Board Member card
  src/app/board/page.js
  src/components/board/Board.jsx
Labels: Board Page

#99 Mobile responsivness for Project page
  src/components/ProjectDescription.jsx
Labels: Projects Page, Ready To Review

#138 Add header animation
  src/components/Header.jsx
Labels: Ready To Review, animation

#137 Remove react imports
  src/app/about/page.js
  src/app/board/page.js
  src/app/not-found.js
  src/app/projects/page.js
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/ProjectDescription.jsx
  src/components/ProjectTitle.jsx
  src/components/VerticalText.jsx
  src/components/about/AboutSection.jsx
  src/components/board/Board.jsx
  src/components/events/EventDescription.jsx
  src/components/events/EventDescriptions.jsx
  src/components/events/UpcomingEvents.jsx
  src/components/home/FocusCard.jsx
  src/components/home/FocusCards.jsx
  src/components/home/JoinCard.jsx
  src/components/home/JoinCards.jsx
  src/components/home/JoinUsSection.jsx
  src/components/home/Landing.jsx
  src/components/home/ProjectsSection.jsx
  src/components/home/ProjectsTab.jsx
  src/components/home/WhatWeDoSection.jsx
  src/components/home/WhatWeDoTitle.jsx
  src/components/home/WhoWeAreSection.jsx
  src/components/projects/Title.jsx
Labels: Ready To Review

#136 Optimize bootstrap imports
  src/components/home/FocusCards.jsx
  src/components/home/JoinCards.jsx
Labels: Ready To Review

#135 Define Props Explicitly
  src/components/ProjectDescription.jsx
Labels: Ready To Review

#134 removal of 'use client' and moving 'use client' into children modules…
  src/components/events/EventDescriptions.jsx
  src/components/home/FocusCards.jsx
  src/components/home/JoinCards.jsx
  src/components/home/JoinUsSection.jsx
  src/components/home/WhatWeDoSection.jsx
Labels: Ready To Review

#133 animate join us
  src/components/home/JoinCards.jsx
Labels: About Page, Ready To Review
