Repository acm-ucr/asme-website, pull requests merged in 2023-07, with the labels that each got.

#23 Safe duck/who we are section
  src/components/WhoWeAreSection.jsx
Labels: Home Page, Ready To Review

#24 Create Join Cards
  src/components/JoinCard.jsx
  src/components/JoinUsSection.jsx
Labels: Ready To Review

#27 Create Navigation
  package-lock.json
  package.json
  src/components/MenuItem.jsx
  src/components/Navigation.jsx
Labels: Navigation, Ready To Review

#26 landing page header
  src/app/layout.js
  src/components/Landing.jsx
  tailwind.config.js
Labels: Home Page

#28 fix side scrolling issue
  src/components/WhoWeAreSection.jsx
Labels: Home Page, Ready To Review

#25 Create title of What To Do section
  src/components/WhatWeDoSection.jsx
Labels: Ready To Review

#29 footer section: links on click, svg white logo
  public/logo-white.svg
  src/components/Footer.jsx
Labels: Footer, Ready To Review

#31 Header (projects)
  src/components/Header.jsx
Labels: About Page, Projects Page, Events Page, Board Page, Ready To Review

#32 Events Description
  src/components/EventDescription.jsx
Labels: Events Page, Ready To Review

#33 Create Projects Tab
  src/components/ProjectsSection.jsx
  src/components/ProjectsTab.jsx
Labels: Home Page, Projects Page, Ready To Review

#36 Projects section header
  pnpm-lock.yaml
  src/components/ProjectsSection.jsx
  src/components/WhatWeDoSection.jsx
Labels: Home Page, Ready To Review

#37 Join Us Section Title
  src/components/JoinUsSection.jsx
Labels: Home Page, Ready To Review

#35 Fix Join Cards layout when screen size changes
  src/components/JoinCard.jsx
Labels: Home Page, Ready To Review

#34 Create Focus Cards
  src/components/FocusCard.jsx
Labels: Home Page, Ready To Review

#46 Mobile footer
  src/components/Footer.jsx
Labels: Footer, Ready To Review

#53 add 'Upcoming Events' heading
  src/app/events/page.js
  src/components/UpcomingEvents.jsx
Labels: Events Page, Ready To Review

#54 Create section titles on About Page
  next.config.js
  package-lock.json
  package.json
  src/app/about/page.js
  src/components/Title.jsx
Labels: About Page, Ready To Review

#55 Update README.md
  .github/workflows/pull-request.yaml
  README.md
Labels: Ready To Review

#57 Create Projects Page
  src/app/projects/page.js
  src/components/ProjectDescription.jsx
Labels: Projects Page, Ready To Review

#56 Update README.md
  README.md
  pnpm-lock.yaml
Labels: Ready To Review

#59 Fix join us button margin
  src/components/Landing.jsx
Labels: Home Page, Ready To Review

#58 responsify join cards
  src/components/JoinCard.jsx
  src/components/JoinCards.jsx
Labels: Home Page, Ready To Review

#71 Focus Cards responsiveness
  src/components/FocusCard.jsx
  src/components/FocusCards.jsx
Labels: Home Page, Ready To Review
